[package]
name = "rust-chip-8"
version = "0.1.0"
authors = ["Lucas Van Mol <lucas.vanmol@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
either = "1.6.1"
minifb = "0.19.3"
rand = "0.8.4"
